server:
  port: 8082

spring:
  application:
    name: libraryflow-hexagonal-blue
  datasource:
    url: jdbc:h2:mem:libraryflow-blue
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        hbm2ddl.create_namespaces: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
