server:
  port: 8080

spring:
  application:
    name: libraryflow-layered
  datasource:
    url: jdbc:h2:mem:libraryflow
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
