type Book {
    id: ID!
    isbn: String!
    title: String!
    author: String!
    available: Boolean!
}

type BookDetail {
    id: ID!
    isbn: String!
    title: String!
    author: String!
    available: Boolean!
    borrowedBy: String
    dueDate: String
    daysRemaining: Int
}

type UserDetail {
    id: ID!
    name: String!
    email: String!
    activeLoans: Int!
    overdueLoans: Int!
    remainingBorrowSlots: Int!
}

type Loan {
    id: ID!
    bookId: ID!
    userId: ID!
    borrowDate: String!
    dueDate: String!
    returned: Boolean!
}

type Query {
    book(id: ID!): BookDetail
    allBooks: [Book!]!
    availableBooks: [Book!]!
    searchBooks(title: String!, author: String, available: Boolean): [Book!]!
}

type Mutation {
    borrowBook(bookId: ID!, userId: ID!): Loan!
    returnBook(loanId: ID!): Loan!
}
